name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Ruby for use with actions
      uses: actions/setup-ruby@v1.0.0
    - name: Test README.md
      run: |
        gem install awesome_bot
        awesome_bot --allow-ssl README.md
